version: "3"
services:
  postgres:
    container_name: test_db
    image: postgres:12
    environment:
      POSTGRES_DB: test
    volumes:
      - ${HOME}/Volumes5/docker/postgres:/var/lib/postgresql/data
    restart: always
  application:
    container_name: spring_app
    image: test
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always