version: "3"
services:
  postgres:
    container_name: test_db
    image: postgres:11.3
    environment:
      POSTGRES_DB: test
#      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/Volumes/docker/postgres:/var/lib/postgresql/data
    restart: always
  application:
    container_name: test_api
    image: test
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8555:8555"
      - "8666:8666"
    restart: always