version: "3"
services:
  postgres:
    container_name: psql_data
    image: postgres:12
    restart: always
  Application:
    container_name: Spring_app
    image: test
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always